config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  authenticated :user do
    root to: "users#show", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end
  
  resources :genres
  resources :tracks do
    collection do
get :tracks_with_comments_needing_approval
    end
    resources :comments do
      collection do
        put :approve
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :admin
      can :manage, :all

    elsif user.persisted?
      can :create, Track
      can :read, Track
      can :update, Track, user_id: user.id
      can :destroy, Track, user_id: user.id

      can :read, Genre
      can :create, Genre

      can :read, User, id: user.id
      can :update, User, id: user.id

      can :create, Comment
      can :update, Comment
      
    else
      can :read, :all
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  scope :approved, -> { where status: 'approved'}
  scope :draft, -> { where status: 'draft'}
  
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base

  acts_as_commentable

  mount_uploader :track_file, TrackFileUploader
  mount_uploader :track_image, TrackImageUploader

  belongs_to :genre
  belongs_to :user

  def comments_needing_approval
    comments.where(status: "draft")
  end

  def self.with_comments_waiting_approval
    joins(:comments).where(comments:{status: "draft"}).distinct
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :rememberable, :trackable, :validatable

  mount_uploader :user_image, UserImageUploader

before_validation :set_role

  has_many :tracks

  def set_role
    self.role ||= :artist
  end

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_path, alert: "You can't access this page"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @track = Track.find(params[:track_id])
  end

  def create
    @track = Track.find(params[:track_id])
    @comment = @track.comments.new(comment_params)
    @comment.status = "draft"
    @comment.user = current_user
    @comment.save
    redirect_to @track
  end

  def approve
    Comment.where("id IN (?)", params[:comment_ids]).update_all(status: "approved")
    redirect_to track_comments_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to(track_path)
  end

  def comment_params
    params.require(:comment).permit(:title, :comment, :track_id, :status)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  load_and_authorize_resource
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to(@genre)
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to(@genre)
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to(genres_path)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @tracks = Track.all
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  load_and_authorize_resource
  def index
      @tracks = Track.all
    end

    def new
      @track = Track.new
    end

    def create
      @track = current_user.tracks.new(track_params)
      @track.save
      redirect_to(@track)
    end

    def show
      @track = Track.find(params[:id])
    end

    def edit
      @track = Track.find(params[:id])
    end

    def update
      @track = Track.find(params[:id])
      @track.update(track_params)
      redirect_to(@track)
    end

    def destroy
      @track = Track.find(params[:id])
      @track.destroy
      redirect_to(tracks_path)
    end

    def tracks_with_comments_needing_approval
      @tracks = Track.with_comments_waiting_approval
      render :index
    end

    def track_params
      params.require(:track).permit(:name, :genre_id, :details, :user_id, :track_file, :track_image)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to(@user)
  end

  def user_params
    params.require(:user).permit(:email, :user_image, :bio, :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
</div>

app/views/comments/index.html.erb
<div class="small-8 small-centered columns">
  <h5>Comments for the track titled: <%= @track.name %></h5>
  <hr>
  <h5>Moderation table</h5>
  <%= form_tag approve_track_comments_path, method: :put do %>
  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Comment</th>
      <th>Status</th>

    </tr>

    <% @track.comments.draft.each do |comment| %>
    <tr>
      <td><%= check_box_tag "comment_ids[]", comment.id %></td>
      <td><%= comment.user_id %> </td>
      <td><%= comment.comment %></td>
      <td><%= comment.status%></td>
      <td></td>
      
    </tr>
    <% end %>
  </table>
  <%= submit_tag "Approve Comments", class: "tiny button" %> 
  <% end %>

  <h5>All Approved Comments</h5>
  <table>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Comment</th>
      <th>Status</th>

    </tr>
    <% @track.comments.approved.each do |comment| %>
    <tr>
      <td><%= comment.id %></td>
      <td><%= comment.user_id %></td>
      <td><%= comment.comment %></td>
      <td><%= comment.status%></td>

    </tr>
    <% end %>
  </table>

  <hr>
</div>

app/views/genres/_genre_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>
<br>

app/views/genres/edit.html.erb
<div class="small-4 small-centered columns">
  <%= form_for @genre do |f| %>
  <%= render partial: 'genre_form', locals: { f: f } %>
  <%= f.submit 'Edit the genre!', class: "tiny button" %>
  <% end %>
</div>

app/views/genres/index.html.erb
<div class="small-4 small-centered columns">
  <% @genres.each do |genre| %>
  <h2><%= genre.name %></h2>
  <%= link_to "Show", genre, class: "tiny button" %>
  <%= link_to "Edit", edit_genre_path(genre), class: "tiny button" if can? :edit, genre %>
  <%= link_to "Delete!", genre_path(genre), method: :delete, data: {confirm: "Are you sure"}, class: "tiny button" if can? :destroy, genre %>
  <% end %>
</div>

app/views/genres/new.html.erb
<div class="small-4 small-centered columns">
  <%= form_for @genre do |f| %>
  <%= render partial: 'genre_form', locals: { f: f } %>
  <%= f.submit 'Add the genre!', class: "tiny button" %>
  <% end %>
</div>

app/views/genres/show.html.erb
<div class="small-4 small-centered columns">
  <h2><%= @genre.name %></h2>

  <% if @genre.tracks.any? %>

      <h3>Tracks in this category:</h3>
      <% @genre.tracks.each do |track| %>
        <%= link_to track.name, track_path(track) %><br>
      <% end %>
   <% else %>
     <p>No tracks have been added to this genre </p>
  <% end %>

  <%= link_to 'Back', genres_path, class: "tiny button" %>
</div>

app/views/home/index.html.erb
<div class="small-6 small-centered columns">
  <h1>Welcome to SoundRails</h1>
  <h2>Sign up for more great features</h2>
<%= link_to 'Sign Up!', new_user_registration_path, class: "tiny button" %>

  <% @tracks.each do |track| %>
  <div>
    <%= image_tag track.track_image.thumb.url %>
    <h2><%= track.name %></h2>

    <%= link_to "Show", track, class: "tiny button" %>

    <% end %>
  </div>
  <hr>
  
</div>

app/views/layouts/_menu.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'SoundRails', tracks_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="left">
        <li class='login'></li>
        <% if current_user %>
        <li class="username"><%= current_user.email %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
      <!-- Right Nav Section -->
      <ul class="right">
        <li><%= link_to 'Profile', authenticated_root_path %></li>
        <li class="has-dropdown">
          <%= link_to 'Genres', genres_path %>
          <ul class="dropdown">
            <li><%= link_to 'All Genres', genres_path %></li>
            <li><%= link_to 'New Genre', new_genre_path if can? :create, @genre %></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <%= link_to 'Tracks', tracks_path %>
          <ul class="dropdown">
            <li><%= link_to 'All Tracks', tracks_path %></li>
            <li><%= link_to 'New Track', new_track_path if can? :create, @track %></li>
          </ul>
        </li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "SoundRails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render partial: "layouts/menu" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  

    <footer>
      <p> SoundRails &copy MMXIV</p>
    </footer>

</body>
</html>

app/views/tracks/_track_form.html.erb
<div>
<%= f.label :name %>
<%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :genre_id, 'Genre' %><br>
  <%= f.collection_select(:genre_id, Genre.all, :id, :name) %>
</div>
  
<%= f.label :details %>
<%= f.text_area :details %>

<div class="field">
    <%= f.label :track_file %><br />
    <%= f.file_field :track_file %>
</div>

<div class="field">
    <%= f.label :track_image %><br />
    <%= f.file_field :track_image %>
</div>

app/views/tracks/edit.html.erb
<div class="small-6 small-centered columns">
<%= form_for @track do |f| %>
<%= render partial: 'track_form', locals: { f: f } %>
<%= f.submit 'Edit Track!', class: "tiny button" %>
<% end %>
</div>

app/views/tracks/index.html.erb
<div class="small-6 small-centered columns">
  <h1>Choose a track</h1>

  <% @tracks.each do |track| %>
  <div>
    <%= image_tag track.track_image.thumb.url %>
    <h2><%= track.name %></h2>

    <%= link_to "Show", track, class: "tiny button" %>
    <%= link_to "Edit", edit_track_path(track), class: "tiny button" if can? :edit, track %>
    <%= link_to "Delete!", track_path(track), method: :delete, data: {confirm: "Are you sure"}, class: "tiny button" if can? :destroy, track %>
    <%= link_to 'Approve comments', track_comments_path(track), class: "tiny button" if can?(:approve, track) && track.comments_needing_approval.any? %>
    <% end %>
  </div>
  <hr>
  <%= link_to 'New Track', new_track_path, class: "tiny button" %>
</div>

app/views/tracks/new.html.erb
<div class="small-6 small-centered columns">
<%= form_for @track do |f| %>
<%= render partial: 'track_form', locals: { f: f } %>
<%= f.submit 'Add Track!', class: "tiny button" %>
</div>
<% end %>
</div>

app/views/tracks/show.html.erb
<div class="small-6 small-centered columns">
  <%= image_tag @track.track_image.thumb.url %>
  <h2><%= @track.name %></h2>
  
  <div>
    <h3>Added by:</h3>
    <p><%= @track.user.try :email %></p>
  </div>

  <audio controls="controls" source src="<%= @track.track_file.url %>" />    
    </audio>
  <hr>
  
  <%= form_for [@track, Comment.new] do |f| %>
  <%= render partial: 'comments/form', locals: { f: f } %>
  <%= f.submit 'Add Comment!', class: "tiny button" %>
  <% end %>

  <% @track.comments.approved.each do |comment| %>
  <%= image_tag(comment.user.user_image.thumb.url) %>
  <%= comment.comment %>
  <br>
  <p>Posted by: <%= comment.user.try :email %></p>
  <p>Date: <%= comment.user.try :created_at  %>
  <hr>
  <% end %>
  <br>

  <%= link_to 'Edit', edit_track_path(@track), class: "tiny button" if can? :edit, @track %>
  <%= link_to 'Back', tracks_path, class: "tiny button" %>
</div>

app/views/users/_form.html.erb
<div class="field">
    <%= f.label :user_image %><br>
    <%= f.file_field :user_image %>
</div>
<div>
  <%= f.label :bio %><br>
  <%= f.text_area :bio %>
</div>

app/views/users/edit.html.erb
<div class="small-6 small-centered columns">
<%= form_for @user do |f| %>
<%= render partial: 'form', locals: { f: f } %>
<%= f.submit 'Edit Profile!', class: "tiny button" %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="small-6 small-centered columns">
<h1>Latest Tracks</h1>
</div>

app/views/users/show.html.erb
<div class="small-8 small-centered columns">

  <div class="profile-pic">
    <%= image_tag @user.user_image.profile.url, class: "profile-pic" %>
  </div>

  <h1><%= @user.email %></h1>

  <h2>Bio:</h2>
  <%= @user.bio %>
  <hr>
  
  <% if @user.tracks.any? %>
    <h2>Tracks:</h2>
    <% @user.tracks.each do |track| %>
      <div>
      <%= image_tag track.track_image.thumb.url %>
      <h3><%= track.name %></h3>
      <%= link_to "Show", track, class: "tiny button" %>
      <%= link_to "Edit", edit_track_path(track), class: "tiny button" %>
      <%= link_to "Delete!", track_path(track), class: "tiny button", method: :delete, data: {confirm: "Are you sure"} if can? :destroy, track %>
    </div>
    <% end %>
    <hr>
  <% end %>

  <%= link_to "Comments needing approval", tracks_with_comments_needing_approval_tracks_path, class: "tiny button" if can? :update, Comment %>
  <%= link_to "Edit profile", edit_user_path(@user), class: "tiny button" if can? :update, User%>
</div>